-
  name: Install Nginx and server static website  
  hosts: prd
  become: yes
  tasks:  
    - name: Install Nginx 
      apt:  
        name: nginx
        state: latest

    - name: Start nginx  
      service:  
        name: nginx
        state: started 
        enabled: yes

    - name: Deploy web pages  
      copy:  
        src: index.html
        dest: /var/www/html



          

